name: Prek auto-update
on:
  schedule:
    # Run on mondays at midnight
    - cron: "0 0 * * 1"

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.1

      - name: Set up Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: "3.x"

      - name: Install prek
        run: pip install prek

      - name: Run prek auto-update
        run: prek auto-update

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update/prek-auto-update
          title: Auto-update pre hooks
          commit-message: Auto-update prek hooks
          body: |
            Update versions of hooks in prek
            configs to latest version
          labels: dependencies
